In [5]:
def calculate_bonus(salary, performance_rating):
    if performance_rating not in (1,2,3,4,5):
        raise ValueError("rating musi być od 1 do 5")
    if type(salary) is not int:
        raise TypeError ("salary musi być liczbą")
    if performance_rating == 5:
        bonus =  0.2*salary
    elif performance_rating == 4:
        bonus =  0.1 * salary
    else:
        bonus = 0
    return bonus

In [6]:
try:
    calculate_bonus("pięć tysięcy", 3)
except TypeError as e:
    print(f"Błąd typu: {e}")
except ValueError as e:
    print(f"Błąd wartości: {e}")

Błąd typu: salary musi być liczbą


In [27]:
def even_numbers(n):
    for i in range(0, n+1):
        if i%2 == 0:
            yield i

In [28]:
for num in even_numbers(10):
    print(num)  # 0, 2, 4, 6, 8, 10

0
2
4
6
8
10


In [29]:
import numpy as np

In [32]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

In [41]:
a + b

array([11, 22, 33, 44, 55])

In [42]:
a * 3

array([ 3,  6,  9, 12, 15])

In [46]:
b.sum()

np.int64(150)

In [47]:
b.mean()

np.float64(30.0)

In [48]:
b.std()

np.float64(14.142135623730951)

In [52]:
a > 2

array([False, False,  True,  True,  True])

In [53]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [54]:
A * B

array([[ 5, 12],
       [21, 32]])

In [55]:
A @ B

array([[19, 22],
       [43, 50]])

In [56]:
A.T

array([[1, 3],
       [2, 4]])

In [57]:
A.shape

(2, 2)